<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Lengow\Model;

use Lengow\Model\Base\LengowExcludeProduct as BaseLengowExcludeProduct;

/**
 * Class LengowExcludeProduct
 * @package Lengow\Model
 */
class LengowExcludeProduct extends BaseLengowExcludeProduct
{
}
