<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Lengow\Model;

use Lengow\Model\Base\LengowIncludeAttribute as BaseLengowIncludeAttribute;

/**
 * Class LengowIncludeAttribute
 * @package Lengow\Model
 */
class LengowIncludeAttribute extends BaseLengowIncludeAttribute
{
}
