<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Lengow\Model;

use Lengow\Model\Base\LengowExcludeCategory as BaseLengowExcludeCategory;

/**
 * Class LengowExcludeCategory
 * @package Lengow\Model
 */
class LengowExcludeCategory extends BaseLengowExcludeCategory
{
}
