<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Lengow\Loop;

use Lengow\Loop\Base\LengowExcludeCategory as BaseLengowExcludeCategoryLoop;

/**
 * Class LengowExcludeCategory
 * @package Lengow\Loop
 */
class LengowExcludeCategory extends BaseLengowExcludeCategoryLoop
{
    /**
     * You may now add your own logic
     */
}
