<?php
/*************************************************************************************/
/*      This file is part of the Thelia package.                                     */
/*                                                                                   */
/*      Copyright (c) OpenStudio                                                     */
/*      email : dev@thelia.net                                                       */
/*      web : http://www.thelia.net                                                  */
/*                                                                                   */
/*      For the full copyright and license information, please view the LICENSE.txt  */
/*      file that was distributed with this source code.                             */
/*************************************************************************************/

namespace Lengow\Controller;
use Thelia\Controller\Admin\ExportController as BaseExportController;
use Thelia\Core\FileFormat\Archive\AbstractArchiveBuilder;
use Thelia\Core\FileFormat\Formatting\AbstractFormatter;
use Thelia\ImportExport\Export\ExportHandler;
use Thelia\Model\Lang;

/**
 * Class ExportTool
 * @package Lengow\Controller
 * @author Benjamin Perche <bperche@openstudio.fr>
 */
class ExportTool extends BaseExportController
{
    public function processExport(
        AbstractFormatter $formatter,
        ExportHandler $handler,
        AbstractArchiveBuilder $archiveBuilder = null,
        Lang $lang,
        $includeImages = false,
        $includeDocuments = false
    )
    {
        return parent::processExport($formatter, $handler, $archiveBuilder, $lang, $includeImages, $includeDocuments); // TODO: Change the autogenerated stub
    }

} 